name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write service account to file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-key.json

      - name: Deploy to Firebase
        run: firebase deploy --project=discord-c0a31 --token "$(cat firebase-key.json | jq -r .private_key_id)" --only hosting
